version: '3'

includes:
  dc: ./Taskfile.devcontainer.yml

env:
  BUILD_CACHE: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

vars:
  BUILD_TYPE: "'{{if .BUILD_TYPE}}{{.BUILD_TYPE}}{{else}}dev-test{{end}}"
  # REGISTRY: docker.io
  REGISTRY: 'registry.localhost'
  GIT_HASH:
    sh: git log -1 --format=%h
  GIT_TAG:
    sh: git describe --tags --always

tasks:
  # Build ------------------------------------
  build-service-3:
    desc: Build Service 1
    cmds:
      - |
        docker -l warn build \
        {{- if not .BUILD_CACHE }}--no-cache \{{end}}
        --build-arg BUILD_TYPE={{.BUILD_TYPE}} \
        --build-arg GIT_HASH={{.GIT_HASH}} \
        --build-arg GIT_TAG={{.GIT_TAG}} \
        --target {{.BUILD_TYPE}} \
        --tag {{.REGISTRY}}/service-3:latest \
        --file Dockerfile .

  run-service-3:
    desc: Run Service 3
    deps: [build-service-3]
    cmds:
      - |
        docker run -it --rm --network="host" \
        {{.REGISTRY}}/service-3:latest
