version: '3'

vars:
  CLUSTER_NAME: tech-stack
  ELASTICSEARCH_VERSION: 19.11.0 # app version: 8.9.1
  KIBANA_VERSION: 10.5.0 # app version: 8.9.1
  LOGSTASH_VERSION: 5.5.0 # app version: 8.9.1
  MONGODB_VERSION: 13.16.4 # app version: 6.0.8
  POSTGRESQL_VERSION: 12.8.2 # app version: 15.4.0
  PROMETHEUS_VERSION: 0.2.0 # app version: 2.46.0
  REDIS_VERSION: 17.15.4 # app version: 7.2.0

tasks:
  install-k3d:
    desc: Create k3d cluster
    cmds:
      - k3d cluster create tech-stack --config k3d-cluster.yml

  uninstall-k3d:
    desc: Delete k3d cluster
    cmds:
      - k3d cluster delete tech-stack

  install-nginx-controller:
    desc: Install nginx controller
    vars:
      APP_VERSION: 1.9.4
    cmds:
      - cmd: kubectl create namespace ingress-nginx
        ignore_error: true
      - kubectl apply -f ../../charts/tech-stack/ingress/controller/nginx/manifests/nginx-ingress.{{.APP_VERSION}}.yaml
      - kubectl -n ingress-nginx get svc
      - kubectl apply -f ../../charts/tech-stack/ingress/controller/nginx/features/routing-by-path-rewrite.yaml

  uninstall-nginx-controller:
    desc: Uninstall nginx controller
    vars:
      APP_VERSION: 1.9.4
    cmds:
      - kubectl delete -f ../../charts/tech-stack/ingress/controller/nginx/features/routing-by-path-rewrite.yaml
      - kubectl delete -f ../../charts/tech-stack/ingress/controller/nginx/manifests/nginx-ingress.{{.APP_VERSION}}.yaml
      - kubectl delete namespace ingress-nginx

  # https://artifacthub.io/packages/helm/bitnami/elasticsearch
  install-elasticsearch:
    desc: Install elasticsearch
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm install elasticsearch bitnami/elasticsearch --version {{.ELASTICSEARCH_VERSION}} --values values.elasticsearch.yaml

  uninstall-elasticsearch:
    desc: Uninstall elasticsearch
    cmds:
      - helm delete elasticsearch

  purge-elasticsearch:
    desc: Purge elasticsearch
    cmds:
      - cmd: task uninstall-elasticsearch
        ignore_error: true
      - cmd: helm delete --purge elasticsearch
        ignore_error: true
      # - kubectl delete pvc elasticsearch # TODO

  # https://artifacthub.io/packages/helm/bitnami/kibana
  install-kibana:
    desc: Install kibana
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm install kibana bitnami/kibana --version {{.KIBANA_VERSION}} --values values.kibana.yaml

  uninstall-kibana:
    desc: Uninstall kibana
    cmds:
      - helm delete kibana

  purge-kibana:
    desc: Purge kibana
    cmds:
      - cmd: task uninstall-kibana
        ignore_error: true
      # - kubectl delete pvc kibana # TODO

  # https://artifacthub.io/packages/helm/bitnami/logstash
  install-logstash:
    desc: Install logstash
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm install logstash bitnami/logstash --version {{.LOGSTASH_VERSION}} --values values.logstash.yaml

  uninstall-logstash:
    desc: Uninstall logstash
    cmds:
      - helm delete logstash

  purge-logstash:
    desc: Purge logstash
    cmds:
      - cmd: task uninstall-logstash
        ignore_error: true
      # - kubectl delete pvc logstash # TODO

  # https://artifacthub.io/packages/helm/bitnami/mongodb
  install-mongodb:
    desc: Install mongodb
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm install mongodb bitnami/mongodb --version {{.MONGODB_VERSION}} --values values.mongodb.yaml

  uninstall-mongodb:
    desc: Uninstall mongodb
    cmds:
      - helm delete mongodb

  purge-mongodb:
    desc: Purge mongodb
    cmds:
      - cmd: task uninstall-mongodb
        ignore_error: true
      - kubectl delete pvc mongodb

  port-forward-mongodb:
    desc: Port forward mongodb
    cmds:
      - lsof -t -i:27017 | xargs -r kill -9
      - kubectl port-forward deployment/mongodb 27017:27017

  # https://artifacthub.io/packages/helm/bitnami/postgresql
  install-postgresql:
    desc: Install postgresql
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm install postgresql bitnami/postgresql --version {{.POSTGRESQL_VERSION}} --values values.postgresql.yaml

  uninstall-postgresql:
    desc: Uninstall postgresql
    cmds:
      - helm delete postgresql

  purge-postgresql:
    desc: Purge postgresql
    cmds:
      - cmd: task uninstall-postgresql
        ignore_error: true
      - kubectl delete pvc data-postgresql-0

  port-forward-postgresql:
    desc: Port forward postgresql
    cmds:
      - lsof -t -i:5432 | xargs -r kill -9
      - kubectl port-forward postgresql-0 5432:5432

  shell-postgresql:
    desc: Log into postgresql shell
    cmds:
      - |
        export POSTGRES_ADMIN_PASSWORD=$(kubectl get secret --namespace default postgresql -o jsonpath="{.data.postgres-password}" | base64 -d) &&
        PGPASSWORD="$POSTGRES_PASSWORD" psql --host 127.0.0.1 -U admin -d tech_stack_db -p 5432

  # https://artifacthub.io/packages/helm/bitnami/prometheus
  install-prometheus:
    desc: Install prometheus
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm install prometheus bitnami/prometheus --version {{.PROMETHEUS_VERSION}} --values values.prometheus.yaml

  uninstall-prometheus:
    desc: Uninstall prometheus
    cmds:
      - helm delete prometheus

  purge-prometheus:
    desc: Purge prometheus
    cmds:
      - cmd: task uninstall-prometheus
        ignore_error: true
      # - kubectl delete pvc data-prometheus-0 # TODO

  # https://artifacthub.io/packages/helm/bitnami/redis
  install-redis:
    desc: Install redis
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm install redis bitnami/redis --version {{.REDIS_VERSION}} --values values.redis.yaml

  uninstall-redis:
    desc: Uninstall redis
    cmds:
      - helm delete redis

  purge-redis:
    desc: Purge redis
    cmds:
      - cmd: task uninstall-redis
        ignore_error: true
      - kubectl delete pvc redis-data-redis-master-0

  port-forward-redis:
    desc: Port forward redis
    cmds:
      - lsof -t -i:6379 | xargs -r kill -9
      - kubectl port-forward redis-master-0 6379:6379

  install-dependencies:
    desc: Install dependencies
    cmds:
      - task: install-mongodb
      - task: install-postgresql
      - task: install-redis

  uninstall-dependencies:
    desc: Uninstall dependencies
    cmds:
      - cmd: task uninstall-mongodb
        ignore_error: true
      - cmd: task uninstall-postgresql
        ignore_error: true
      - cmd: task uninstall-redis
        ignore_error: true

  generate-charts:
    desc: Generate charts
    cmds:
      - cd ../../../k8s/charts/tech-stack && task update-dependency
      - helm template tech-stack ../../../k8s/charts/tech-stack --include-crds --values values.yaml > /tmp/output.yaml
