version: '3'

vars:
  CLUSTER_NAME: tech-stack
  POSTGRES_VERSION: 12.8.2 # app version: 15.4.0

tasks:
  k3d-create:
    desc: Create k3d cluster
    cmds:
      - k3d cluster create tech-stack --config k3d-cluster.yml

  k3d-delete:
    desc: Delete k3d cluster
    cmds:
      - k3d cluster delete tech-stack

  install-postgresql:
    desc: Install postgresql
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm install postgresql bitnami/postgresql --version {{.POSTGRES_VERSION}}

  uninstall-postgresql:
    desc: Uninstall postgresql
    cmds:
      - helm delete postgresql

  purge-postgresql:
    desc: Purge postgresql
    cmds:
      - cmd: task uninstall-postgresql
        ignore_error: true
      - kubectl delete pvc data-postgresql-0
