version: '3'

vars:
  CLUSTER_NAME: tech-stack
  MONGODB_VERSION: 13.16.4 # app version: 6.0.8
  POSTGRESQL_VERSION: 12.8.2 # app version: 15.4.0
  REDIS_VERSION: 17.15.4 # app version: 7.2.0

tasks:
  create-k3d:
    desc: Create k3d cluster
    cmds:
      - k3d cluster create tech-stack --config k3d-cluster.yml

  delete-k3d:
    desc: Delete k3d cluster
    cmds:
      - k3d cluster delete tech-stack

  # https://artifacthub.io/packages/helm/bitnami/mongodb
  install-mongodb:
    desc: Install mongodb
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm install mongodb bitnami/mongodb --version {{.MONGODB_VERSION}} --values values.mongodb.yaml

  uninstall-mongodb:
    desc: Uninstall mongodb
    cmds:
      - helm delete mongodb

  purge-mongodb:
    desc: Purge mongodb
    cmds:
      - cmd: task uninstall-mongodb
        ignore_error: true
      - kubectl delete pvc mongodb-data-mongodb-master-0

  # https://artifacthub.io/packages/helm/bitnami/postgresql
  install-postgresql:
    desc: Install postgresql
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm install postgresql bitnami/postgresql --version {{.POSTGRESQL_VERSION}} --values values.postgresql.yaml

  uninstall-postgresql:
    desc: Uninstall postgresql
    cmds:
      - helm delete postgresql

  purge-postgresql:
    desc: Purge postgresql
    cmds:
      - cmd: task uninstall-postgresql
        ignore_error: true
      - kubectl delete pvc data-postgresql-0

  # https://artifacthub.io/packages/helm/bitnami/redis
  install-redis:
    desc: Install redis
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm install redis bitnami/redis --version {{.REDIS_VERSION}} --values values.redis.yaml

  uninstall-redis:
    desc: Uninstall redis
    cmds:
      - helm delete redis

  purge-redis:
    desc: Purge redis
    cmds:
      - cmd: task uninstall-redis
        ignore_error: true
      - kubectl delete pvc redis-data-redis-master-0

  install-dependencies:
    desc: Install dependencies
    cmds:
      - task: install-postgresql
      - task: install-redis

  uninstall-dependencies:
    desc: Uninstall dependencies
    cmds:
      - cmd: task uninstall-postgresql
        ignore_error: true
      - cmd: task uninstall-redis
        ignore_error: true
