version: '3'

vars:
  CLUSTER_NAME: tech-stack

tasks:
  k3d-create:
    desc: Create k3d cluster
    cmds:
      - k3d cluster create tech-stack --config k3d-cluster.yml

  k3d-delete:
    desc: Delete k3d cluster
    cmds:
      - k3d cluster delete tech-stack

  install-postgresql:
    desc: Install postgresql
    cmds:
      - helm install postgresql oci://registry-1.docker.io/bitnamicharts/postgresql

  uninstall-postgresql:
    desc: Uninstall postgresql
    cmds:
      - helm delete postgresql

  purge-postgresql:
    desc: Purge postgresql
    cmds:
      - cmd: task uninstall-postgresql
        ignore_error: true
      - kubectl delete pvc data-postgresql-0
