# https://github.com/bitnami/charts/blob/main/bitnami/elasticsearch/values.yaml

# global:
#   kibanaEnabled: true

master:
  masterOnly: true
  replicaCount: 1

data:
  replicaCount: 1

coordinating:
  replicaCount: 1

ingest:
  enabled: true
  replicaCount: 1
