version: '3'

includes:
  dc: ./Taskfile.devcontainer.yml

env:
  BUILD_CACHE: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

vars:
  BUILD_TYPE: "'{{if .BUILD_TYPE}}{{.BUILD_TYPE}}{{else}}dev-test{{end}}"
  # REGISTRY: docker.io
  REGISTRY: 'registry.localhost'
  GIT_HASH:
    sh: git log -1 --format=%h
  GIT_TAG:
    sh: git describe --tags --always

tasks:
  # Build ------------------------------------
  build-migrations:
    desc: Build migrations
    cmds:
      - |
        docker -l warn build \
        {{- if not .BUILD_CACHE }}--no-cache \{{end}}
        --build-arg BUILD_TYPE={{.BUILD_TYPE}} \
        --build-arg GIT_HASH={{.GIT_HASH}} \
        --build-arg GIT_TAG={{.GIT_TAG}} \
        --target {{.BUILD_TYPE}} \
        --tag {{.REGISTRY}}/migrations:latest \
        --file Dockerfile .

  run-migrations:
    desc: Run migrations
    deps: [build-migrations]
    cmds:
      - |
        docker run -it --rm --network="host" \
        registry.localhost/migrations:latest
