version: '3'

tasks:
  update-dependency:
    desc: Generate helm dependencies
    cmds:
      - helm dependency update

  show-templates:
    deps: [update-dependency]
    desc: Render chart templates
    cmds:
      - helm template --debug tech-stack ./ --include-crds --values values.yaml
